package HellDiverMacro;

public interface StratagemList {
	static String[][] name = {
			{"Resupply", "sswd "},
			{"MG-94 Machine Gun", "saswd "},
			{"MGX-42 Machine Gun", "saswwa "},
			{"LAS-98 Laser Cannon", "saswa "},
			{"AC-22 Dum-Dum", "saswwd "},
			{"Obliterator Grenade Launcher", "sawas "},
			{"M-25 Rumbler", "sawaa "},
			{"FLAM-40 Incinerator", "sasda "},
			{"TOX-13 Avenger", "sasdd "},
			{"RL-112 Recoilless Rifle", "sadda "},
			{"EAT-17", "sadws "},
			{"MLS-4X Commando", "sawsd "},
			{"AD-334 Guard Dog", "swawds "},
			{"AD-289 Angel", "swaads "},
			{"Resupply Pack", "swssd "},
			{"LIFT-850 Jump Pack", "swwsw "},
			{"SH-32 Directional Kinetic Shield", "swadas "},
			{"SH-20 Shield Generator Pack", "swadad "},
			{"REP-80", "ssads "},
			{"REC-6 Demolisher", "sadww "},
			{"EXO-44 Walker Exosuit", "sdwass "},
			{"EXO-48 Obsidian Exosuit", "sdwasa "},
			{"EXO-51 Lumberer Exosuit", "sdwasd "},
			{"MC-109 Hammer Motorcycle", "sdsaaw "},
			{"TD-110 Bastion", "sdsawd "},
			{"M5 APC", "sdsaad "},
			{"M5-32 HAV", "sdsaws "},
			{"Humblebee UAV drone", "awd "},
			{"Distractor Beacon", "asd "},
			{"AT-47 Anti-Tank Emplacement", "aawwda "},
			{"A_MG-II Minigun Turret", "aswda "},
			{"A_RX-34 Railcannon Turret", "aswad "},
			{"A_GL-8 Launcher Turret", "aswdds "},
			{"A_AC-6 Tesla Tower", "asswda "},
			{"Airdropped Anti-Personnel Mines", "adsw "},
			{"Anti-Personnel Barrier", "adssd "},
			{"Thunderer Smoke Round", "dswws "},
			{"Airdropped Stun Mines", "adws "},
			{"Static Field Conductors", "dwas "},
			{"Heavy Airstrike", "dwsda "},
			{"Vindicator Dive Bomb", "ddd "},
			{"Strafing Run", "ddw "},
			{"Incendiary Bombs", "dwad "},
			{"Heavy Strafing Run", "ddsw "},
			{"Close Air Support", "ddsa "},
			{"Missile Barrage", "dsssas "},
			{"Thunderer Barrage", "dswwas "},
			{"Sledge Precision Artillery", "dwawsd "},
			{"Orbital Laser Strike", "dwawda "},
			{"Shredder Missile Strike", "dadassd "},
			{"Railcannon Strike", "dswsa "},
			{"Stratagem ", ""},
			{"Reinforce", "wsdaw "},
			{"NUX-223 Hellbomb", "wadsws "},
			{"ME-1 Sniffer Metal Detector", "ssdw "},
			{"Emergency Beacon", "wsdw "}
	};
	
}
